name: footware_admin
description: "A Footware Application Admin Panel"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

